//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCKimlik.IdentityService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tckimlik.nvi.gov.tr/WS", ConfigurationName="IdentityService.KPSPublicV2Soap")]
    public interface KPSPublicV2Soap {
        
        // CODEGEN: Generating message contract since element name Ad from namespace http://tckimlik.nvi.gov.tr/WS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tckimlik.nvi.gov.tr/WS/KisiVeCuzdanDogrula", ReplyAction="*")]
        global::TCKimlik.IdentityService.KisiVeCuzdanDogrulaResponse KisiVeCuzdanDogrula(global::TCKimlik.IdentityService.KisiVeCuzdanDogrulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tckimlik.nvi.gov.tr/WS/KisiVeCuzdanDogrula", ReplyAction="*")]
        System.Threading.Tasks.Task<global::TCKimlik.IdentityService.KisiVeCuzdanDogrulaResponse> KisiVeCuzdanDogrulaAsync(global::TCKimlik.IdentityService.KisiVeCuzdanDogrulaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KisiVeCuzdanDogrulaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KisiVeCuzdanDogrula", Namespace="http://tckimlik.nvi.gov.tr/WS", Order=0)]
        public global::TCKimlik.IdentityService.KisiVeCuzdanDogrulaRequestBody Body;
        
        public KisiVeCuzdanDogrulaRequest() {
        }
        
        public KisiVeCuzdanDogrulaRequest(global::TCKimlik.IdentityService.KisiVeCuzdanDogrulaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tckimlik.nvi.gov.tr/WS")]
    public partial class KisiVeCuzdanDogrulaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long TCKimlikNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Soyad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool SoyadYok;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> DogumGun;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool DogumGunYok;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<int> DogumAy;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool DogumAyYok;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int DogumYil;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string CuzdanSeri;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.Nullable<int> CuzdanNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string TCKKSeriNo;
        
        public KisiVeCuzdanDogrulaRequestBody() {
        }
        
        public KisiVeCuzdanDogrulaRequestBody(long TCKimlikNo, string Ad, string Soyad, bool SoyadYok, System.Nullable<int> DogumGun, bool DogumGunYok, System.Nullable<int> DogumAy, bool DogumAyYok, int DogumYil, string CuzdanSeri, System.Nullable<int> CuzdanNo, string TCKKSeriNo) {
            this.TCKimlikNo = TCKimlikNo;
            this.Ad = Ad;
            this.Soyad = Soyad;
            this.SoyadYok = SoyadYok;
            this.DogumGun = DogumGun;
            this.DogumGunYok = DogumGunYok;
            this.DogumAy = DogumAy;
            this.DogumAyYok = DogumAyYok;
            this.DogumYil = DogumYil;
            this.CuzdanSeri = CuzdanSeri;
            this.CuzdanNo = CuzdanNo;
            this.TCKKSeriNo = TCKKSeriNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KisiVeCuzdanDogrulaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KisiVeCuzdanDogrulaResponse", Namespace="http://tckimlik.nvi.gov.tr/WS", Order=0)]
        public global::TCKimlik.IdentityService.KisiVeCuzdanDogrulaResponseBody Body;
        
        public KisiVeCuzdanDogrulaResponse() {
        }
        
        public KisiVeCuzdanDogrulaResponse(global::TCKimlik.IdentityService.KisiVeCuzdanDogrulaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tckimlik.nvi.gov.tr/WS")]
    public partial class KisiVeCuzdanDogrulaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool KisiVeCuzdanDogrulaResult;
        
        public KisiVeCuzdanDogrulaResponseBody() {
        }
        
        public KisiVeCuzdanDogrulaResponseBody(bool KisiVeCuzdanDogrulaResult) {
            this.KisiVeCuzdanDogrulaResult = KisiVeCuzdanDogrulaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KPSPublicV2SoapChannel : global::TCKimlik.IdentityService.KPSPublicV2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KPSPublicV2SoapClient : System.ServiceModel.ClientBase<global::TCKimlik.IdentityService.KPSPublicV2Soap>, global::TCKimlik.IdentityService.KPSPublicV2Soap {
        
        public KPSPublicV2SoapClient() {
        }
        
        public KPSPublicV2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KPSPublicV2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KPSPublicV2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KPSPublicV2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::TCKimlik.IdentityService.KisiVeCuzdanDogrulaResponse global::TCKimlik.IdentityService.KPSPublicV2Soap.KisiVeCuzdanDogrula(global::TCKimlik.IdentityService.KisiVeCuzdanDogrulaRequest request) {
            return base.Channel.KisiVeCuzdanDogrula(request);
        }
        
        public bool KisiVeCuzdanDogrula(long TCKimlikNo, string Ad, string Soyad, bool SoyadYok, System.Nullable<int> DogumGun, bool DogumGunYok, System.Nullable<int> DogumAy, bool DogumAyYok, int DogumYil, string CuzdanSeri, System.Nullable<int> CuzdanNo, string TCKKSeriNo) {
            global::TCKimlik.IdentityService.KisiVeCuzdanDogrulaRequest inValue = new global::TCKimlik.IdentityService.KisiVeCuzdanDogrulaRequest();
            inValue.Body = new global::TCKimlik.IdentityService.KisiVeCuzdanDogrulaRequestBody();
            inValue.Body.TCKimlikNo = TCKimlikNo;
            inValue.Body.Ad = Ad;
            inValue.Body.Soyad = Soyad;
            inValue.Body.SoyadYok = SoyadYok;
            inValue.Body.DogumGun = DogumGun;
            inValue.Body.DogumGunYok = DogumGunYok;
            inValue.Body.DogumAy = DogumAy;
            inValue.Body.DogumAyYok = DogumAyYok;
            inValue.Body.DogumYil = DogumYil;
            inValue.Body.CuzdanSeri = CuzdanSeri;
            inValue.Body.CuzdanNo = CuzdanNo;
            inValue.Body.TCKKSeriNo = TCKKSeriNo;
            global::TCKimlik.IdentityService.KisiVeCuzdanDogrulaResponse retVal = ((global::TCKimlik.IdentityService.KPSPublicV2Soap)(this)).KisiVeCuzdanDogrula(inValue);
            return retVal.Body.KisiVeCuzdanDogrulaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<global::TCKimlik.IdentityService.KisiVeCuzdanDogrulaResponse> global::TCKimlik.IdentityService.KPSPublicV2Soap.KisiVeCuzdanDogrulaAsync(global::TCKimlik.IdentityService.KisiVeCuzdanDogrulaRequest request) {
            return base.Channel.KisiVeCuzdanDogrulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<global::TCKimlik.IdentityService.KisiVeCuzdanDogrulaResponse> KisiVeCuzdanDogrulaAsync(long TCKimlikNo, string Ad, string Soyad, bool SoyadYok, System.Nullable<int> DogumGun, bool DogumGunYok, System.Nullable<int> DogumAy, bool DogumAyYok, int DogumYil, string CuzdanSeri, System.Nullable<int> CuzdanNo, string TCKKSeriNo) {
            global::TCKimlik.IdentityService.KisiVeCuzdanDogrulaRequest inValue = new global::TCKimlik.IdentityService.KisiVeCuzdanDogrulaRequest();
            inValue.Body = new global::TCKimlik.IdentityService.KisiVeCuzdanDogrulaRequestBody();
            inValue.Body.TCKimlikNo = TCKimlikNo;
            inValue.Body.Ad = Ad;
            inValue.Body.Soyad = Soyad;
            inValue.Body.SoyadYok = SoyadYok;
            inValue.Body.DogumGun = DogumGun;
            inValue.Body.DogumGunYok = DogumGunYok;
            inValue.Body.DogumAy = DogumAy;
            inValue.Body.DogumAyYok = DogumAyYok;
            inValue.Body.DogumYil = DogumYil;
            inValue.Body.CuzdanSeri = CuzdanSeri;
            inValue.Body.CuzdanNo = CuzdanNo;
            inValue.Body.TCKKSeriNo = TCKKSeriNo;
            return ((global::TCKimlik.IdentityService.KPSPublicV2Soap)(this)).KisiVeCuzdanDogrulaAsync(inValue);
        }
    }
}
